### ISSUE TITLE
landfill destroys boats and signals

### ISSUE THREAD

**Issue by bghira** [rudegrass/cargo_ships#43]
was looking through the source and can't find anything that can be done about this. any ideas?

**Comment by squidy5** [comment]
sorry for not replying, i havent been active on this project in the last couple of months. 

since i cant stop the landfill to be placed, only replace the old tiles afterwards, its difficult to fix this behaviour.

On the other hand the behaviour is not terribly unexpected i guess, and while maybe annoying not game-breaking, so i wont try to find a possible fix right now.
