### ISSUE TITLE
Oil rigs fail on surfaces other than Nauvis

### ISSUE THREAD

**Issue by robot256** [rudegrass/cargo_ships#52]
When using Space Exploration to generate other surface worlds with bodies of water, oil rigs do not build properly.  There are still a few lines of code that use `game.surfaces[1]` instead of `entity.surface`.

**Comment by robot256** [comment]
Tested working fixed in this branch: https://github.com/robot256/cargo_ships/tree/actual_0-57

I can make a pull request once you upload version 0.0.57 to your repo.

**Comment by squidy5** [comment]
Thanks for your contributions and sorry for not replying. I havent really been very active regarding this project latley. I updated the repository to the current version, and merged the pull request you made a few weeks ago.
Maybe the issue is already resolved then? If not I d be happy to merge any further pull request!

**Comment by robot256** [comment]
The fix for this one was more involved, so I'll make another pull request.  Glad to help!

**Comment by robot256** [comment]
Turns out my fix for this got rolled into the other pull request already.  There was one new change that wasn't (not mandatory but nice to have) that I made a new PR for just now.  This issue is closed now.  Thanks!
