### ISSUE TITLE
entity error when launched

### ISSUE THREAD

**Issue by LegendaryGeek** [rudegrass/cargo_ships#60]
i was playing the factorio seablock mod pack with cargo ships, and upon creating the world, i get this unrecoverable error: 
```
The mod Cargo Ships (0.0.60) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event cargo-ships-seraph::on_chunk_generated (ID 12)
Unknown entity name: deep_oil
stack traceback:
	[C]: in function 'create_entity'
	__cargo-ships-seraph__/logic/oil_placement.lua:63: in function <__cargo-ships-seraph__/logic/oil_placement.lua:3>
```

**Comment by robot256** [comment]
The issue was that Seablock deleted the `deep_oil` entity but did not disable the oil placement setting in Cargo Ships.  This should be fixed with Seablock version 0.5.5 and higher, with no change required to Cargo Ships.

Since it is fixed elsewhere now, and this user was using the [Seraph fork ](https://github.com/Seraphendipity/cargo_ships) rather than this repository anyways, I believe this issue can be closed now.
